#%RAML 1.0 NamedExample
- sourceSystem: FirstData
  transactionId: a123456789
  dateTime: 2018-08-18T12:13:14Z
  currency: 
    code: USD
  amount: 154.44
  method: CreditCard
  paymentInfo:
    cardType: VISA
    creditCardNumber: "1234567812345678"
    cardOwner: Brett Roeder
    expirationDate: 
      month: 8
      year: 2018
    ccv: "874"
    postalCode: "301683"
  approved: true
  additionalInfo: Additional info   
- sourceSystem: TSYS
  transactionId: a2334568684
  dateTime: 2018-08-18T12:13:14Z
  currency: 
    code: USD
  amount: 154.44
  method: CreditCard
  paymentInfo:
    cardType: VISA
    creditCardNumber: "1234567812345678"
    cardOwner: Brett Roeder
    expirationDate: 
      month: 8
      year: 2018
    ccv: "874"
    postalCode: "301683"
  approved: true
  additionalInfo: Additional info 