#%RAML 1.0
title: Order SAP API
baseUri: http://localhost/{version}
version: v1
mediaType: [application/json, application/xml]
securedBy: [passthrough]
securitySchemes: 
  passthrough: !include /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/pass-through-security-scheme/1.0.0/pass-through-security-scheme.raml

description: This API expose Order related functionality living in SAP.

uses: 
  order: /exchange_modules/66234019-5a31-4239-ba28-4e6d70f0468a/order-library/1.0.18/order-library.raml
  collectionRT: /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/collection-library/1.0.24/collection-library.raml

/orders:
  type:  
    collectionRT.collection:
      mediaType: application/json
  get:
    queryParameters: 
      orderId?: 
        minLength: 3
      customerId?:
        minLength: 3
      productId?: 
        minLength: 3
      productName?:
        minLength: 3
      startDate?: date-only
      endDate?: date-only
  post:
  /{id}:
    type: 
      collectionRT.member:
        mediaType: application/json
    uriParameters: 
      id:
        example: "1"
        default: "1"
    get:
    put:
    delete:
